<?php

namespace CF\MarsubookBundle\Repository;

/**
 * MarsuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarsuRepository extends \Doctrine\ORM\EntityRepository
{
}
